### ISSUE TITLE
Generate more fine-grained JS ?

### ISSUE THREAD

**Issue by vendethiel** [notslang/yade#9]
Hi ! I've been, as I think you have, a long-time jade lover.
There's only one thing that bugs me (apart from being unable to use coffee/ls as code) : the code it generates is slow. It's gotten better now, but it's still far too slow compared to "JS html".
Since I had a very specific use case, I created [nephrite](https://github.com/nami-doc/nephrite), which allowed me to cut everything I wanted (I didn't need escaping, for example, since it's for an userscript and I trust all data).
As you can see, it generates a near-"perfect" JS, since it doesn't use `with` (new jade shouldn't use it either, but is a bit "broken" because it prefixes all variables. Nephrite uses `@` prefix, because I think it makes the most sense). I doesn't use "attrs", since it's also very very slow, and never necessary. I really don't know why it's here... Even with escaping, it could generate the static `attrname=`. Last thing would be escape, but I know most cases need it (shouldn't be any hard to add tho).

The only problem is : the code is utter crap. What I'm basically doing is converting 

``` jade
for a in b
  if a.b % 2
    = a.b
```

to

```
| #{(for a in b then """
| #{if a.b % 2 then """
| #{a.b}
| """ else ""}
| """).join ''}
```

then coffee/coco/livescript compiles it down.
Are you any interested in cleaning the jade generated code or something?

**Comment by notslang** [comment]
I actually started semantic-jade because I was annoyed with the designer-friendly logical operations, because they basically just look like coffeescript... so I wanted to use coffeescript in my templates. I wasn't very bothered by the JS it generates (though I do plan to make it more efficient).

As for generating static attributes, and removing escaping, both of these things are a huge pain because interpolation can be used ANYWHERE in jade. Which is a feature that I like, but also means we must be very careful about the way we deal with variables (another reason why I wanted to rely on CoffeeScript for a lot of this - because CoffeeScript has interpolation built in).

Anyway, I'm interested in improving the JS that Jade makes, but I'd do it inside of the compiler because the compiler is already quite mature, it just needs some optimizations.

**Comment by vendethiel** [comment]
I don't want to remove escaping, i just need a way to disable it. Even a no-op return a; costs so much ... Nephrite's code is as fast as simple "html interpolations", jade was around 4 times slower.

**Comment by notslang** [comment]
but why would you want to disable escaping? without escaping, simple characters like quotes will screw up the resulting JS

**Comment by vendethiel** [comment]
Am talking about HTML escaping.

**Comment by vendethiel** [comment]
Anyway, I won't be able to look before september since I only have my phone and 3g.

**Comment by notslang** [comment]
isn't that part of the same function? also, jade already has `!=` for disabling html escaping.

**Comment by vendethiel** [comment]
See discussion in visionmedia/jade#945

**Comment by vendethiel** [comment]
Jade has != but no !{} for interp, and it's painful.

**Comment by vendethiel** [comment]
> isn't that part of the same function?

Maybe. Doesn't change much, It could have a "escapeAttributeQuote" function.

**Comment by notslang** [comment]
ah, that discussion makes a little more sense. anyway, if you wanna disable escaping, just replace the escaping function with a dummy function... it'll get called about the same but it won't have any impact on performance.

Also, don't measure performance with how many calls a function gets, use the total amount of time that function takes to execute.

**Comment by vendethiel** [comment]
I can tell you, even a no-op took a lot of time. See my Pull Requests (#4 #5, I think) at qqueue/c4 to see our discussion about how to get the best performances. I was allowed a 10% margin max ... No comprise :(

**Comment by notslang** [comment]
look at the optimization that Forbes Lindsay mentioned... that could actually offer a big performance boost

>  There is a big, unrelated, win to be made by fixing it so that the attrs stuff gets done more at compile time, which should simplify runtime.js significantly, which makes supporting more browsers easier.

**Comment by vendethiel** [comment]
Yeah, but until something really does it, that's just "an optimization that could maybe be made"

**Comment by notslang** [comment]
yeah.... so if you want jade to be faster, you should do that

**Comment by vendethiel** [comment]
Not really possible considering how features depend on others in the current jade compiler, it's really hard to maintain, best we can do is hack. (Well, still far better than stylus's codebase :p)

**Comment by notslang** [comment]
no, it's entirely possible... a bit time consuming, but it is definitely possible. it wouldn't even pose a breaking change.

**Comment by vendethiel** [comment]
No, it probably wouldn't, but it still would generate a lot more than needed. Also, a main point of interest is co{co,ffeescript}/ls syntax

**Comment by notslang** [comment]
generate a lot more of what than needed?

**Comment by vendethiel** [comment]
JS code

**Comment by notslang** [comment]
no, it would generate less than it currently does because it would be optimized
